In [1]:
[j**4 for j in range (1,9)]

[1, 16, 81, 256, 625, 1296, 2401, 4096]

In [13]:
import numpy as np
x=[1,2,3,4,5,6]
y=np.array(x)
print(y)
print(y.ndim)

[1 2 3 4 5 6]
1


In [7]:
 x=[]
for i in range (2,6):
    int_1=int(input("Enter :"))
    x.append(int_1)
    ##append means add new obj in exeisting array.
print(np.array(x))

Enter :1
Enter :2
Enter :3
Enter :4
['1' '2' '3' '4']


In [8]:
##2 dimentional array
ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [1]:
##3d array
import numpy as np
ar3=([[[1,2,3,4,5],[3,4,5,6,7],[8,6,56,5,4]]])
print(np.array(ar3))

[[[1, 2, 3, 4, 5], [3, 4, 5, 6, 7], [8, 6, 56, 5, 4]]]


In [3]:
arn=np.array([1,2,3,4,5,6,7,8,9],ndmin=10)
print(np.array(arn))
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5 6 7 8 9]]]]]]]]]]
10


# zero

In [24]:
import numpy as nop
ar_zero=nop.zeros(4)
ar_zero1=nop.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones

In [25]:
ar_one=nop.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# identity matrix

In [26]:
ar_dia=nop.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
ar_dia=nop.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linespace

In [32]:
ar_lin=nop.linspace(0,30,num=7)
print(ar_lin)

[ 0.  5. 10. 15. 20. 25. 30.]



# Random

In [4]:
from numpy import random
import numpy as np
var=np.random.rand(10)
print(var)

[0.0893074  0.95472797 0.5154717  0.53045434 0.74921184 0.84877596
 0.71469754 0.37732507 0.28122702 0.31179396]


In [6]:
var1=np.random.rand(2,5)
print(var1)

[[0.53128299 0.93321925 0.88727111 0.79083431 0.15241103]
 [0.46494613 0.29944489 0.3112756  0.60423787 0.63662134]]


In [7]:
vr2=np.random.randn(5)
print(vr2)

[-0.26280222 -0.32383061 -1.33567271 -1.896439    1.91227157]


In [8]:
vr3=np.random.ranf(5)
print(vr3)

[0.472504   0.47039987 0.95310581 0.94722797 0.85607191]


In [17]:
vr4=np.random.randint(100,500,10)
print(vr4)

[360 261 306 177 388 380 381 254 386 155]


# Data Type (numpy)

In [18]:
var5=np.array([1,3,4,6,8,9])
print("data type :",var5.dtype)

data type : int32


In [26]:
vr6=np.array([1,2,3,4,5,6,7,8,9],dtype=np.int64)
print(vr6.dtype)


int64


In [29]:
vr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float32)
print(vr7.dtype)

float32


# choice

In [34]:
x=random.choice([3,4,6,7,8,9,0,1,23,4,5])
print(x)

5


In [36]:
x=random.choice([3,4,6,7,8,9,0,1,23,4,5],size=(4,3))
print(x)

[[ 1  7  8]
 [ 5  4  0]
 [ 4  8 23]
 [ 9  0  7]]


# data distribution (choice)

In [37]:
x=random.choice([1,2,3,5,7,8,676,5,4,4,67],p=[.1,.2,.05,.02,.03,.03,.07,.2,.04,.06,.2],size=8)
print(x)

[  5   5 676   4 676   2   4  67]


In [38]:
x=random.choice([1,2,3,5,7,8,676,5,4,4,67],p=[.1,.2,.05,.02,.03,.03,.07,.2,.04,.06,.2],size=(4,3))
print(x)

[[67 67  4]
 [ 5  4  8]
 [ 5 67 67]
 [ 4  5 67]]


# Resheap

In [48]:
vr7=np.array([2,3,4,5,6,7,8,9])
print(vr7)
print()
x=vr7.reshape(4,2)
print(x)
print()
print(x.ndim)

[2 3 4 5 6 7 8 9]

[[2 3]
 [4 5]
 [6 7]
 [8 9]]

2


# Arithmetic Operation(numpy)

In [52]:
import numpy as np
vr8=np.array([2,3,4,5,6])
vr9=np.array([12,13,14,15,16])
var_add=vr8 + 10
print(var_add)

print()

var_add2=vr8 + vr9 
print(var_add2)

[12 13 14 15 16]

[14 16 18 20 22]


In [55]:
import numpy as np
vr8=np.array([2,3,4,5,6])
vr9=np.array([12,13,14,15,16])
var_add2=vr9 % vr8
print(var_add2)

[0 1 2 0 4]


In [54]:
import numpy as np
vr8=np.array([2,3,4,5,6])
vr9=np.array([12,13,14,15,16])
var_add2=vr8 - vr9
print(var_add2)

[-10 -10 -10 -10 -10]


In [56]:
import numpy as np
vr8=np.array([2,3,4,5,6])
vr9=np.array([12,13,14,15,16])
var_add2=vr8 * vr9
print(var_add2)

[24 39 56 75 96]


In [58]:
import numpy as np
vr10=np.array([[2,3,4,5,6],[9,8,7,6,5]])
vr11=np.array([[12,13,14,15,16],[12,34,56,78,54]])
var_add3=vr10 + vr11
print(var_add3)

[[14 16 18 20 22]
 [21 42 63 84 59]]


In [3]:
import numpy as np
vr10=np.array([[2,3,4,5,6],[9,8,7,6,5]])
vr11=np.array([[12,13,14,15,16],[12,34,56,78,54]])
var_add3=vr11 - vr10
print(var_add3)

[[10 10 10 10 10]
 [ 3 26 49 72 49]]


In [4]:
vr7=np.array([2,3,4,5,6,7,8,9])
print("min: ",np.min(vr7))

min:  2


In [5]:
vr7=np.array([2,3,4,5,6,7,8,9])
print("max: ",np.max(vr7))

max:  9


In [6]:
vr7=np.array([2,3,4,5,6,7,8,9])
print("min: ",np.argmax(vr7))##argmin /argmax eta minimum or maximum er position bole day

min:  7


In [7]:
vr7=np.array([[2,3,4,6],[6,5,8,9]])
print(np.min(vr7,axis=0))##axis=0 row er minimum,axis=1 colum er minimum

[2 3 4 6]


In [8]:
vr7=np.array([[2,3,4,6],[6,5,8,9]])
print(np.sqrt(vr7))

[[1.41421356 1.73205081 2.         2.44948974]
 [2.44948974 2.23606798 2.82842712 3.        ]]


# Cumsum

In [9]:
var10=np.array([1,2,3])
print(np.cumsum(var10))

[1 3 6]


# Broadcasting

In [1]:
import numpy as np
vir1=np.array([1,2,3])
vir2=np.array([[1],[2],[3]])
print(vir1)
print(vir1.shape)
print()
print(vir2)
print(vir2.shape)
print()
print(vir1 + vir2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# nditer() funtion. ..multiple loop  = nditer()

In [15]:
vir3=np.array([[[1,2,3,4,5],[4,5,6,7,8]]])
print(vir3.ndim)
print()
vir4=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(vir4.ndim)
print()

for i in np.nditer(vir3):
    print(i)
print()

for i in np.nditer(vir3,flags=['buffered'],op_dtypes=["S"]):
    print(i)

3

2

1
2
3
4
5
4
5
6
7
8

b'1'
b'2'
b'3'
b'4'
b'5'
b'4'
b'5'
b'6'
b'7'
b'8'


In [18]:
vir5=np.array([[[1,2,3,4,5],[4,5,6,7,8]]])
for i in np.nditer(vir3):
    print(i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 1, 3) 7
(0, 1, 4) 8


# JOIN stack works in row and dstake woths in colum

In [23]:
import numpy as np
arr1 = np.array([1, 2, 3,7,5])
arr2 = np.array([4, 5, 6,9,6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)
print()
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 2 3 7 5]
 [4 5 6 9 6]]

[[1 4]
 [2 5]
 [3 6]
 [7 9]
 [5 6]]


# split

In [24]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Suffel, Unique, resize, flatten, ravel

In [3]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)


[1 3 2 5 4]


In [4]:
var5=np.array([1,4,7,4,3,5,7,75,4,3,5,7,4,3,2,2,4,6,5,3,3])
x=np.unique(var5)
print(x)
print()
var5=np.array([1,4,7,4,3,5,7,75,4,3,5,7,4,3,2,2,4,6,5,3,3])
x=np.unique(var5,return_index=True,return_counts=True)
print(x)

[ 1  2  3  4  5  6  7 75]

(array([ 1,  2,  3,  4,  5,  6,  7, 75]), array([ 0, 14,  4,  1,  5, 17,  2,  7], dtype=int64), array([1, 2, 5, 5, 3, 1, 3, 1], dtype=int64))


In [5]:
var2=([1,2,3,4,5,6])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
var5=([1,2,3,4,5,6,7,8])
x=np.insert(var5,2,50)
print(x)
print()
y=np.insert(var5,[2,3], 40)
print(y)

[ 1  2 50  3  4  5  6  7  8]

[ 1  2 40  3 40  4  5  6  7  8]


# Insert and delet

In [13]:
var5=np.array([[[1,2,3],[4,5,6]]])
x=np.insert(var5,2,[7,8,9],axis=1)
print(x)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
var5=np.array([1,2,3,4,5,6,7,8])
x=np.delete(var5,2)
print(x)
print()
y=np.delete(var5,[2,3])
print(y)

[1 2 4 5 6 7 8]

[1 2 5 6 7 8]


# matrix

In [22]:
var5=np.matrix([[1,2,3],[4,5,6]])
var6=np.matrix([[6,2,9],[1,34,3]])
print(var5 + var6)

[[ 7  4 12]
 [ 5 39  9]]


In [26]:
var5=np.matrix([[1,2,3],[4,5,6],[45,65,7]])
var6=np.matrix([[6,2,9],[1,34,3],[5,78,32]])
print(var5*var6)


[[  23  304  111]
 [  59  646  243]
 [ 370 2846  824]]


# Baler matrix er 14 gusti

# transpose

In [29]:
var5=np.matrix([[1,2,3],[4,5,6]])
print(var5)
print()
print(np.transpose(var5))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [34]:
var5=np.matrix([[1,2,3],[4,5,6]])
#swap axis
print()
print(np.swapaxes(var5,0,1))


[[1 4]
 [2 5]
 [3 6]]


In [38]:
var5=np.matrix([[1,2],[4,5]])
#inverse
print(np.linalg.inv(var5))


[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [ ]:
var5=np.matrix([[1,2],[4,5]])
#inverse
print(np.linalg.inv(var5))