In [2]:
import tensorflow as tf

In [2]:
x=tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
x=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float64)
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [4]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [5]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
x=tf.eye(3)  #eye for identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [7]:
x=tf.random.normal((3,3), mean=12, stddev=6) #will be random martix but if i check standerd deviation and mean then it will be 6&12. that means may be the matrix is random but i can specifie those mean median mode stasnderd deviation etc
print(x)

tf.Tensor(
[[ 7.3522024  5.514503  15.748936 ]
 [16.696117  20.409176   2.5856066]
 [13.236532   9.653796  17.672413 ]], shape=(3, 3), dtype=float32)


In [8]:
x=tf.random.uniform((5,3), minval=2 ,maxval=5) #rules same as above
print(x)

tf.Tensor(
[[2.5586166 4.5848603 4.3638644]
 [2.2442727 2.365437  2.674676 ]
 [2.7967892 2.4834046 2.4084826]
 [3.6443014 4.454049  4.400514 ]
 [3.4389672 2.242019  4.8380194]], shape=(5, 3), dtype=float32)


In [9]:
x=tf.range(20,dtype=tf.float64) # same way also write x=tf.range(20)
print(x)

tf.Tensor(
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.], shape=(20,), dtype=float64)


In [10]:
x=tf.range(start=1, limit=20)
print(x)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], shape=(19,), dtype=int32)


In [11]:
x=tf.range(start=1, limit=20, delta=3)#similar to python
print(x)

tf.Tensor([ 1  4  7 10 13 16 19], shape=(7,), dtype=int32)


In [12]:
x=tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([ 1.  4.  7. 10. 13. 16. 19.], shape=(7,), dtype=float64)


In [13]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y)
a=y-x
b=x*y
c=x/y
print(z)
print(a)
print(b)
print(c)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([8 6 4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [14]:
r=tf.tensordot(x,y,axes=1) #element wise multiplication then add all (21+16+19) see privious code
print(r)

tf.Tensor(46, shape=(), dtype=int32)


In [15]:
z=tf.reduce_sum(x*y,axis=0)#alternative
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [16]:
z=x**3
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [17]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
z = x @ y#alternative .....# Perform matrix multiplication using the @ operator
print(z)

tf.Tensor(
[[ 0.08931929 -0.3091725   0.52100986  1.7137859 ]
 [-0.78914255 -0.04987147  0.14040835  0.16723226]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.08931929 -0.3091725   0.52100986  1.7137859 ]
 [-0.78914255 -0.04987147  0.14040835  0.16723226]], shape=(2, 4), dtype=float32)


In [22]:
x=tf.constant([1,2,1,2,1,3,4,5,6,7,8,9])
print(x[:])

tf.Tensor([1 2 1 2 1 3 4 5 6 7 8 9], shape=(12,), dtype=int32)


In [23]:
x=tf.constant([1,2,1,2,1,3,4,5,6,7,8,9]) #same as python
print(x[2:5])

tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [25]:
indices=tf.constant([0,3]) #related to previous code
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [27]:
x=tf.constant([[1,2],[4,5],[6,7]])
print(x[0])
print(x[0,:])
print(x[0:2])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [30]:
x=tf.range(9)
print(x)
x=tf.reshape(x,(3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [3]:
fill_tensor=tf.fill([2,3],9)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
